### PR TITLE
Update Logo

### PR DESCRIPTION
**Pull request by pizzakid25**
I've created a new version of the logo based on the Google Drive 2020 Q4 logo. Both the logo.png and icon.png files have been updated.

### CODE REVIEW

**Comment by pizzakid25** [comment]
Sorry, I didn't realise the repository.json change would affect the pull request. This is my first time doing this. I believe I undid the change.

**Review by KTibow — APPROVED** [review]
LGTM, a much-needed update.

**Comment by KTibow** [comment]
?

**Comment by pizzakid25** [comment]
Creating a new pull request so that I can modify other things in my fork.

**Comment by pizzakid25** [comment]
@KTibow, sorry for the confusion. My new PR also enlarges the logo and icon files. Thanks for understanding.

**Pull request closed without merging**
